version: '2.1'
services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'

    volumes:
      - /home/user/projects/todo_app /var/lib/mysql
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - '.:/todo_app'
    ports:
      - '3001:3000'
    depends_on:
      - db
    links:
      - db
    environment:
       DB_USER: todo
       DB_NAME: todo
       DB_PASS: password
       DB_HOST: db
